### ISSUE TITLE
Changing "Daemon Server File Location" does not work

### ISSUE THREAD

**Issue by ET-Bent** [Pterodactyl/Daemon#17]
When changing the `Daemon Server File Location` upon node installation, server files will still be under `/srv/daemon-data/`. Only the sftp path is changed.

It seems that the daemon does not use the sftp location for server installation.

**Comment by DaneEveritt** [comment]
I'm not encountering this issue. The panel properly reflects the location in the configuration provided, and the daemon appears to be using that properly.

Could you explain further?
