### ISSUE TITLE
Container DNS override

### ISSUE THREAD

**Issue by topjor** [Pterodactyl/Daemon#25]
I am having a problem where the container can not download the server files. it keeps giving a error that it can't resolve the hostname.
In certain cases other DNS servers are blocked or otherwise not reachable other then internal ones.

I would like a config option for overriding the DNS servers set to each container.
Alternatively it could also not be configured when rebuilding the container, then it would use the systems DNS servers

**Comment by DaneEveritt** [comment]
Interesting, we are using `8.8.8.8` and `8.8.4.4` for the DNS servers, but I will add a method to change these for all containers, or disable it completely and use the host DNS.

Sorry about that. In the mean time, you can manually change the DNS servers assigned to servers by editing the file below and modify the values in the highlighted region.

https://github.com/Pterodactyl/Daemon/blob/release/0.2.0-beta/src/controllers/docker.js#L352-L355

**Comment by DaneEveritt** [comment]
This is available in `v0.2.1` if you upgrade to that version. 😄
